### ISSUE TITLE
small bug in ProcessHollowing.cpp

### ISSUE THREAD

**Issue by peta909** [theevilbit/injection#1]
Hi there,
Thank you for sharing your code .

in processhollowing.cpp,

`	if (!ReadFile(hFile, lpFileBuffer, dwFileSize, NULL, NULL))//bug here!
	{
		TerminateProcess(pProcessInfo->hProcess, 1);
		ErrorExit(TEXT("ReadFile"));
	}`

the 4th param for ReadFile() cant be NULL but it require a pointer to a NULL value that will increase as the file is being read. without the pointer there would be an exception being thrown from WIndows.

I modified the code to the following

`	if (!ReadFile(hFile, lpFileBuffer, dwFileSize, &bytesRead, NULL))//fixed a bug here! &bytesRead is required
	{
		TerminateProcess(pProcessInfo->hProcess, 1);
		ErrorExit(TEXT("ReadFile"));
	}`

**Comment by theevilbit** [comment]
It works also with NULL, but added a parameter, to have a proper code. fixed now.
